<?php
/**
 * JerseyHour — one-time installer.
 * Creates the database, your admin account and default content.
 * Delete this file after installation (the site also locks it automatically).
 */
define('INSTALLER', true);
require __DIR__ . '/includes/bootstrap.php';
require __DIR__ . '/includes/seed.php';

$installed = is_file(APP_ROOT . '/includes/config.php');
$errors = [];
$done = false;

$checks = [
    'PHP 7.4 or newer'                 => version_compare(PHP_VERSION, '7.4.0', '>='),
    'PDO extension'                    => extension_loaded('pdo'),
    'SQLite or MySQL driver'           => extension_loaded('pdo_sqlite') || extension_loaded('pdo_mysql'),
    'includes/ folder is writable'     => is_writable(APP_ROOT . '/includes'),
    'data/ folder is writable'         => is_writable(APP_ROOT . '/data'),
    'uploads/ folder is writable'      => is_writable(APP_ROOT . '/uploads') && is_writable(APP_ROOT . '/uploads/products'),
    'GD image library (for resizing)'  => extension_loaded('gd'),
];
$hasSqlite = extension_loaded('pdo_sqlite');
$hasMysql = extension_loaded('pdo_mysql');

$in = [
    'store_name' => $_POST['store_name'] ?? 'JerseyHour',
    'username'   => $_POST['username'] ?? 'admin',
    'driver'     => $_POST['driver'] ?? ($hasSqlite ? 'sqlite' : 'mysql'),
    'db_host'    => $_POST['db_host'] ?? 'localhost',
    'db_name'    => $_POST['db_name'] ?? '',
    'db_user'    => $_POST['db_user'] ?? '',
    'demo'       => is_post() ? !empty($_POST['demo']) : true,
];

if (!$installed && is_post()) {
    if (!csrf_valid()) $errors[] = 'Session expired — please submit the form again.';
    $pass = (string)($_POST['password'] ?? '');
    $pass2 = (string)($_POST['password2'] ?? '');
    if (!preg_match('~^[A-Za-z0-9_.-]{3,40}$~', $in['username'])) $errors[] = 'Username must be 3–40 characters (letters, numbers, dot, dash, underscore).';
    if (strlen($pass) < 8) $errors[] = 'Password must be at least 8 characters.';
    if ($pass !== $pass2) $errors[] = 'Passwords do not match.';
    if (!in_array($in['driver'], ['sqlite', 'mysql'], true)) $errors[] = 'Choose a database type.';
    if ($in['driver'] === 'sqlite' && !$hasSqlite) $errors[] = 'SQLite is not available on this server — choose MySQL.';
    if ($in['driver'] === 'mysql' && !$hasMysql) $errors[] = 'MySQL driver is not available on this server.';
    if ($in['driver'] === 'mysql' && ($in['db_name'] === '' || $in['db_user'] === '')) $errors[] = 'Enter your MySQL database name and user.';

    if (!$errors) {
        try {
            $cfg = ['path' => '', 'host' => $in['db_host'], 'name' => $in['db_name'], 'user' => $in['db_user'], 'pass' => (string)($_POST['db_pass'] ?? '')];
            if ($in['driver'] === 'sqlite') {
                $cfg['path'] = 'data/jerseyhour-' . bin2hex(random_bytes(8)) . '.sqlite';
            }
            $pdo = db_connect($in['driver'], $cfg);

            if ($in['driver'] === 'mysql' && $pdo->query("SHOW TABLES LIKE 'products'")->fetch()) {
                throw new RuntimeException('This MySQL database already contains JerseyHour tables. Use an empty database.');
            }

            foreach (db_schema($in['driver']) as $sql) {
                $pdo->exec($sql);
            }
            $pdo->beginTransaction();
            seed_settings($pdo, ['store_name' => trim($in['store_name']) ?: 'JerseyHour']);
            seed_pages($pdo);
            $catIds = seed_categories($pdo);
            if ($in['demo']) seed_products($pdo, $catIds);
            $pdo->prepare('INSERT INTO admins (username, password_hash, created_at) VALUES (?, ?, ?)')
                ->execute([$in['username'], password_hash($pass, PASSWORD_DEFAULT), date('Y-m-d H:i:s')]);
            $pdo->commit();

            $x = fn($v) => var_export((string)$v, true);
            $config = "<?php\n// Generated by JerseyHour installer on " . date('Y-m-d H:i') . "\n"
                . "define('DB_DRIVER', " . $x($in['driver']) . ");\n"
                . "define('DB_PATH', " . $x($cfg['path']) . ");\n"
                . "define('DB_HOST', " . $x($cfg['host']) . ");\n"
                . "define('DB_NAME', " . $x($cfg['name']) . ");\n"
                . "define('DB_USER', " . $x($cfg['user']) . ");\n"
                . "define('DB_PASS', " . $x($cfg['pass']) . ");\n"
                . "define('APP_TIMEZONE', 'Asia/Karachi');\n";
            if (file_put_contents(APP_ROOT . '/includes/config.php', $config) === false) {
                throw new RuntimeException('Could not write includes/config.php — make the includes folder writable (755) and try again.');
            }
            @chmod(APP_ROOT . '/includes/config.php', 0640);
            // Try to remove the installer for safety
            @rename(__FILE__, APP_ROOT . '/data/install.php.done');
            $done = true;
        } catch (Throwable $t) {
            if (isset($pdo) && $pdo->inTransaction()) $pdo->rollBack();
            if (!empty($cfg['path']) && is_file(APP_ROOT . '/' . $cfg['path'])) @unlink(APP_ROOT . '/' . $cfg['path']);
            $errors[] = $t->getMessage();
        }
    }
}
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex">
<title>Install JerseyHour</title>
<?= brand_head() ?>
<link rel="stylesheet" href="<?= e(url('admin/assets/admin.css')) ?>">
</head>
<body class="auth-body">
<main class="auth-card install-card">
  <div class="auth-brand"><?= logo_html() ?></div>

<?php if ($installed && !$done): ?>
  <h1>Already installed</h1>
  <p class="muted">JerseyHour is already set up on this server. For security, delete <code>install.php</code> from your hosting.</p>
  <div class="row-actions"><a class="btn btn-primary" href="<?= e(url('admin/login.php')) ?>">Go to admin</a><a class="btn" href="<?= e(url('')) ?>">View store</a></div>

<?php elseif ($done): ?>
  <div class="success-mark"><svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="m5 12 5 5L20 7"/></svg></div>
  <h1>Your store is ready</h1>
  <p class="muted">Sign in with the username <strong><?= e($in['username']) ?></strong> and the password you just set.</p>
  <?php if (is_file(__FILE__)): ?>
    <div class="alert alert-warn">We couldn't remove <code>install.php</code> automatically. Please delete it from your hosting's File Manager.</div>
  <?php else: ?>
    <div class="alert alert-ok">The installer has been locked automatically.</div>
  <?php endif; ?>
  <div class="row-actions"><a class="btn btn-primary" href="<?= e(url('admin/login.php')) ?>">Open admin panel</a><a class="btn" href="<?= e(url('')) ?>">View store</a></div>

<?php else: ?>
  <h1>Set up your store</h1>
  <p class="muted">Takes under a minute. You can change everything later from the admin panel.</p>

  <details class="checks" <?= in_array(false, array_slice($checks, 0, 6), true) ? 'open' : '' ?>>
    <summary>Server check <?= in_array(false, array_slice($checks, 0, 6), true) ? '<span class="pill pill-cancelled">Needs attention</span>' : '<span class="pill pill-delivered">All good</span>' ?></summary>
    <ul>
      <?php foreach ($checks as $label => $ok): ?>
        <li class="<?= $ok ? 'ok' : 'bad' ?>"><?= $ok ? '✓' : '✕' ?> <?= e($label) ?></li>
      <?php endforeach; ?>
    </ul>
  </details>

  <?php foreach ($errors as $err): ?><div class="alert alert-error"><?= e($err) ?></div><?php endforeach; ?>

  <form method="post" class="form" autocomplete="off">
    <?= csrf_field() ?>
    <div class="field">
      <label for="store_name">Store name</label>
      <input id="store_name" name="store_name" value="<?= e($in['store_name']) ?>" required>
    </div>
    <div class="grid-2">
      <div class="field">
        <label for="username">Admin username</label>
        <input id="username" name="username" value="<?= e($in['username']) ?>" required autocomplete="username">
      </div>
      <div class="field">
        <label for="password">Password <span class="hint">min. 8 characters</span></label>
        <input id="password" type="password" name="password" required minlength="8" autocomplete="new-password">
      </div>
    </div>
    <div class="field">
      <label for="password2">Confirm password</label>
      <input id="password2" type="password" name="password2" required minlength="8" autocomplete="new-password">
    </div>

    <fieldset class="field">
      <legend>Database</legend>
      <div class="choice-row">
        <label class="choice"><input type="radio" name="driver" value="sqlite" <?= $in['driver'] === 'sqlite' ? 'checked' : '' ?> <?= $hasSqlite ? '' : 'disabled' ?>>
          <span><strong>Automatic (SQLite)</strong><small>Recommended — nothing to configure</small></span></label>
        <label class="choice"><input type="radio" name="driver" value="mysql" <?= $in['driver'] === 'mysql' ? 'checked' : '' ?> <?= $hasMysql ? '' : 'disabled' ?>>
          <span><strong>MySQL</strong><small>Use a database created in cPanel</small></span></label>
      </div>
    </fieldset>

    <div id="mysql-fields" class="mysql-fields" <?= $in['driver'] === 'mysql' ? '' : 'hidden' ?>>
      <div class="grid-2">
        <div class="field"><label>Host</label><input name="db_host" value="<?= e($in['db_host']) ?>"></div>
        <div class="field"><label>Database name</label><input name="db_name" value="<?= e($in['db_name']) ?>" placeholder="cpaneluser_jersey"></div>
        <div class="field"><label>Database user</label><input name="db_user" value="<?= e($in['db_user']) ?>"></div>
        <div class="field"><label>Database password</label><input type="password" name="db_pass"></div>
      </div>
    </div>

    <label class="switch-row">
      <input type="checkbox" name="demo" value="1" <?= $in['demo'] ? 'checked' : '' ?>>
      <span><strong>Add sample jerseys</strong><small>8 demo products so you can see the design. Edit or delete them anytime.</small></span>
    </label>

    <button class="btn btn-primary btn-block btn-lg" type="submit">Install JerseyHour</button>
  </form>
  <script>
    document.querySelectorAll('input[name=driver]').forEach(function (r) {
      r.addEventListener('change', function () {
        document.getElementById('mysql-fields').hidden = document.querySelector('input[name=driver]:checked').value !== 'mysql';
      });
    });
  </script>
<?php endif; ?>
</main>
</body>
</html>
